// JsFromRoutes CacheKey 460653d60dec7ef397fb4c3135d1d833
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  list: definePathHelper('get', '/pains'),
  create: definePathHelper('post', '/pains'),
  new: definePathHelper('get', '/pains/new'),
  edit: definePathHelper('get', '/pains/:id/edit'),
  get: definePathHelper('get', '/pains/:id'),
  update: definePathHelper('patch', '/pains/:id'),
  destroy: definePathHelper('delete', '/pains/:id'),
}
